### PR TITLE
Beta update/Library rewrite

### PR DESCRIPTION
**Pull request by 999eagle**
This PR isn't going to merge cleanly as I've rewritten large parts of the library. This PR is intended to be used for discussion on how to improve the code.

As I already said, this is a very large rewrite of the entire library and it depends on the latest flutter beta (1.4.9-hotfix.1). Not everything has been reimplemented yet, but flutter apps do work fine. Some parts are still being worked on.

### CODE REVIEW

**Comment by 999eagle** [comment]
I've merged the latest changes from master into this branch and fixed some more issues. The app demo is not yet complete, but otherwise this should work now :)

**Comment by gliheng** [comment]
Good job. Let's merge into master once, 1.4.9-hotfix.1 is on stable channel.

**Comment by gliheng** [comment]
Is this patch ready to merge into beta?

**Comment by 999eagle** [comment]
I've been using this branch for quite a while now and I do feel that this is ready for beta.
The problem is that this branch absolutely requires using flutter beta. Due to changed ffi interfaces this branch will segfault if used with flutter stable.

**Pull request merged**
